(()=>{
  const C=window.EUREKA_CONFIG||{},$=s=>document.querySelector(s),short=a=>a&&a.length>18?`${a.slice(0,8)}…${a.slice(-6)}`:(a||'—');
  const esc=window.Eureka.escape;
  const els={connected:$('#sConnected'),workers:$('#sWorkers'),wallets:$('#sWallets'),epoch:$('#sEpoch'),state:$('#networkState'),body:$('#topMinersBody'),claims:$('#claimsBody')};
  function renderStats(d){const ps=d.public_stats||d;els.connected.textContent=ps.connected_miners??0;els.workers.textContent=ps.active_workers??0;els.wallets.textContent=ps.total_wallets_ever??0;els.state.textContent='API ONLINE';$('#networkDot')?.classList.add('connected');const rows=Array.isArray(ps.top_miners)?ps.top_miners:[];els.body.innerHTML=rows.length?rows.slice(0,20).map(r=>`<tr><td>${esc(r.rank??'—')}</td><td class="wallet-short">${esc(short(r.wallet))}</td><td>${Number(r.accepted_shares||0).toLocaleString()}</td><td>${esc(r.cumulative_eknx||'0')} EKNX</td><td>${r.active?'● Online':'Idle'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No public mining data yet.</td></tr>';const claims=Array.isArray(ps.latest_claims)?ps.latest_claims:[];els.claims.innerHTML=claims.length?claims.slice(0,20).map(r=>`<tr><td>${r.block_time?new Date(r.block_time).toLocaleString():'—'}</td><td class="wallet-short">${esc(short(r.wallet))}</td><td>${esc(r.amount_eknx||'0')} EKNX</td><td>${esc(r.settlement_day??'—')}</td><td>${r.tx_hash?`<a class="text-link" href="https://bscscan.com/tx/${encodeURIComponent(r.tx_hash)}" target="_blank" rel="noopener">BscScan</a>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No on-chain claims yet.</td></tr>'}
  function renderNetwork(d){els.epoch.textContent=d.current_epoch??d.epoch??'—'}
  async function refresh(){if(!C.publicStatsUrl&&!C.networkUrl)return;try{const jobs=[];if(C.publicStatsUrl)jobs.push(fetch(C.publicStatsUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('stats');return r.json()}).then(renderStats));if(C.networkUrl)jobs.push(fetch(C.networkUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('network');return r.json()}).then(renderNetwork));await Promise.all(jobs)}catch{els.state.textContent='Dados indisponíveis / Data unavailable';['connected','workers','wallets','epoch'].forEach(k=>els[k].textContent='—');$('#networkDot')?.classList.remove('connected')}}
  refresh();if(C.publicStatsUrl||C.networkUrl)setInterval(refresh,Math.max(5000,C.statsRefreshMs||15000));
})();
