(()=>{
  const C=window.EUREKA_CONFIG||{}, title=document.getElementById('miningReadiness'), detail=document.getElementById('miningReadinessDetail');
  if(!title||!detail||!C.healthUrl)return;
  let state='checking';
  const messages={pt:{checking:['A verificar a pool…','A disponibilidade do download não confirma que a mineração esteja ativa.'],active:['Mineração ativa','A pool confirma o início da mineração e a aceitação de shares. Configura o miner e verifica o trabalho aceite.'],pending:['A aguardar ativação da mineração','Podes descarregar e configurar o miner. O genesis da mineração ainda não está confirmado pela pool.'],paused:['Mineração indisponível','A pool não está a aceitar trabalho ou a emissão está suspensa. Verifica novamente antes de iniciar.'],unknown:['Estado não confirmado','Não foi possível consultar a pool neste navegador. Consulta o estado diretamente; não assumes que a mineração está ativa.']},en:{checking:['Checking the pool…','Download availability does not confirm that mining is active.'],active:['Mining active','The pool confirms mining activation and share acceptance. Configure your miner and verify accepted work.'],pending:['Waiting for mining activation','You can download and configure the miner. The pool has not yet confirmed the mining genesis.'],paused:['Mining unavailable','The pool is not accepting work or emission is paused. Check again before starting.'],unknown:['Status unconfirmed','This browser could not check the pool. Check its status directly; do not assume mining is active.']}};
  function render(){const m=messages[window.Eureka?.lang()==='en'?'en':'pt'][state];title.textContent=m[0];title.dataset.state=state;detail.textContent=m[1]}
  async function refresh(){try{const r=await fetch(C.healthUrl,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('health');const h=await r.json();state=h.ok!==true?'unknown':!h.genesis_started||Number(h.mining_start_unix)<=0?'pending':h.accept_shares===true&&h.emission_enabled===true?'active':'paused'}catch{state='unknown'}render()}
  addEventListener('eureka:language',render);render();refresh();setInterval(refresh,Math.max(5000,C.statsRefreshMs||15000));
})();
